---
# sass-lint config
# https://github.com/sasstools/sass-lint
#

files:
  include: '**/*.scss'
options:
  formatter: stylish
  merge-default-rules: true
rules:
  clean-import-paths: 0
  indentation: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-mergeable-selectors: 0
  no-qualifying-elements: 0
  property-sort-order: 0
  single-line-per-selector: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
